### ISSUE TITLE
Artificial contribution count inflation

### ISSUE THREAD

**Issue by Soleedus** [URI-CSC/csc-212-s18#7]
Hi. This isn't an issue relevant to the codebase/repository, but rather an issue I noticed with Piazza. I opted to post my concerns here instead of Piazza for reasons that will become obvious.

This might be a bit unreasonably paranoid but I've been receiving a ton of emails from Piazza informing me that my responses/answers as a student are continuously being "enhanced" by an anonymous user. After further analysis, I'm finding quite a few responses being "improved" by an anonymous user with seemingly no changes except for appended whitespace. Some examples include the following posts:

- [Skip](https://piazza.com/class/jcr7oluz6il5ra?cid=253)
- [n_elements](https://piazza.com/class/jcr7oluz6il5ra?cid=249)
- [search](https://piazza.com/class/jcr7oluz6il5ra?cid=262)
- [Autograder error](https://piazza.com/class/jcr7oluz6il5ra?cid=263)
- [Calling prepend from main.cc](https://piazza.com/class/jcr7oluz6il5ra?cid=316)

To test to see if such meaningless edits count towards the Piazza contribution score, I added a few spaces to [this post](https://piazza.com/class/jcr7oluz6il5ra?cid=318) as an anonymous user. Sure enough, my contribution count increased from 72 to 73.

Maybe I'm wrong and this isn't foul play, but it hardly seems coincidental that the top 5 posters on Piazza get extra credit and yet someone could be inflating their contribution counter.

I figured I should let you all know of this as Dr. Alvarez makes a point of maintaining academic integrity. I'm hoping that extra credit will be evaluated not just on the quantity of user contributions/answers but also of their quality. It doesn't seem so absurd or unbelievable to me that someone would try to artificially inflate their post count in some desperate attempt to get the extra credit.

**Comment by MarcoAlvarez** [comment]
Good points.  We will update the policy on extra-credit.
